exports.get=function(name){
	var constant={
					"PAGE_SIZE":2,
					"LOGIN_CERTIFICATE_LENGTH":2,
					"APPLY_CERTIFICATE_TIMEOUT":60*15*1000,
					"CERTIFICATE_KEY_START":0,
					"CERTIFICATE_KEY_MID":16,
					"CERTIFICATE_KEY_GROUP_NUMS":8,
					"CERTIFICATE_KEY_GROUP_START":0,
					"CERTIFICATE_KEY_GROUP_MID":2,
					"STANDARD_START":0,
					"RANDOM_START":899999,
					"RANDOM_OFFSET":100000,
					"RANDOM_MIN_START":8999,
					"RANDOM_MIN_OFFSET":1000
				}
	return constant[name];
}